### ISSUE TITLE
Same noise for mask generation

### ISSUE THREAD

**Issue by gylee1103** [ashual/scene_generation#16]
Thanks for your nice work and sharing the codes. It's really useful to me. 

https://github.com/ashual/scene_generation/blob/e4b98ea437329b1a51deb67811e2b6593baa8ff6/scene_generation/model.py#L149

Sorry if I misunderstand. In the figure in the paper, the noises for generating masks seem different per each object. (z1, z2, ..., zi) But I think the code here repeat the same noises for every object in the batch. May this decrease the performance?

**Comment by ashual** [comment]
Thanks for your kind words.
I've tried both option, and it seems that the github repository ended up with slightly different version from the paper.
In my experiments I didn't notice any different.
 Do you see any different when training/testing this model?

**Comment by gylee1103** [comment]
I didn't test both. I just wanted to know if I misunderstand the codes. Thank you for your reply!
