### ISSUE TITLE
where to find ./models/attributes_{}_{}.pickle in coco.py line 147?

### ISSUE THREAD

**Issue by UBCMark** [ashual/scene_generation#2]
`with open('./models/attribute_{}_{}.pickle'.format(self.size_attribute_len, self.location_attribute_len), 'rb') as f:'  

how to generate './models/attributes_{}_{}.pickle' ?

**Comment by ashual** [comment]
this file basically saves the distribution of the objects' locations and needed only to sample different locations attributes. It's a simple aggregation, but anyway I'll upload the code and the file very soon

**Comment by ashual** [comment]
@UBCMark 
I've added `scripts/create_attributes_file.py` that can generate this file.
you can find this file in the Google Drive directory
