### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by MikeXuQ** [ashual/scene_generation#3]
Hi, I am conducting a research on scene generation but using sketches as input. And I'm really amazed by your work. I want to compare with your work. But it seems that I don't have enough time to train a new model.  I wonder if you could help me with this. Look forward to your feedbacks!

**Comment by ashual** [comment]
Sure,
a trained model will be uploaded in the next few days

**Comment by MikeXuQ** [comment]
Thanks a lot!
